name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 1.8
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          
